### ISSUE TITLE
'HTTP latency' in "SERIES_META" is empty

### ISSUE THREAD

**Issue by zzzuzik** [tohojo/netperf-wrapper#10]
Hi @tohojo,
thanks again for the help with `http-getter`

I have one question for you - is there any way (parameters, settings) to include `MEAN_VALUE` for `HTTP latency` into `SERIES_META`. Because, for now, it is empty:
```json
            "TCP upload BE2": {
                "MEAN_VALUE": 936.8
            }, 
            "HTTP latency": {}, 
            "Ping (ms) avg": {
                "MEAN_VALUE": 1736.3999999999999
            }, 
            "TCP download BE4": {
                "MEAN_VALUE": 725.62
            }, 
            "TCP upload BE4": {
                "MEAN_VALUE": 897.17
            }, 
            "TCP download BE2": {
                "MEAN_VALUE": 712.97
            }, 
            "TCP upload avg": {
                "MEAN_VALUE": 918.6175
            }, 
            "Ping (ms) ICMP": {}, 
```

It is good to have it there because it allows to quickly get needed results of `http-rrul` from `metadata` output without parsing results in json.gz. `Ping (ms) ICMP` will be helpful too.

Thank you for your work.

**Comment by tohojo** [comment]
> I have one question for you - is there any way (parameters, settings)
> to include MEAN_VALUE for HTTP latency into SERIES_META.

Not currently, but it can be added. The idea with the value in
SERIES_META is that it's the average value as output by the test tool
itself (so for instance netperf outputs the mean throughput at the end
of a test). Ping certainly outputs this, and I just patched http-getter
to do so; but it is currently not captures by netperf-wrapper.

Will see if I can find to add the code to netperf-wrapper to parse this
for ping and http-getter sometime tomorrow :)
